name: attendance_monitoring_app
description: A Flutter attendance monitoring application for schools and educational institutions.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.0+1
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  url_launcher: ^6.1.12
  font_awesome_flutter: ^10.7.0
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.7.0
  local_auth: ^2.1.6
  local_auth_android: ^1.0.34
  local_auth_ios: ^1.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1  # ✅ Added

flutter_icons:  # ✅ New section
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png